spring:
 application:
  name: servicios-usuarios
server:
 port: ${PORT:0}
eureka:
  client:
   service-url:
     default-Zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
logging:
  level:
    org:
      hibernate:
        SQL: debug