server:
 port: ${PORT:0}
spring:
 application:
  name: service-celulares
 mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
   service-url:
     default-Zone: http://localhost:8761/eureka
  instance:
    instance-id: ${sping.application.name}:${spring.application.instance_id:${random.value}}